@baseUrl = http://localhost:3000/api/users
### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "cpf": "12345678900",
  "nome": "João da Silva",
  "dataDeNascimento": "1994-05-24T00:00:00.000Z"
}

### Buscar usuário pelo CPF
GET {{baseUrl}}/12345678900

### Listar todos os usuarios
GET {{baseUrl}}